services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: wholesale-app
      POSTGRES_PASSWORD: wholesale-app
      POSTGRES_DB: wholesale-app
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U wholesale-app']
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:5.4.0
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
