// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthLoginPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], false>
}
type AuthLogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type ApiAccountsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/accounts_controller.ts').default['index'], false>
}
type ApiAccountsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/account.ts')['createAccountValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/accounts_controller.ts').default['store'], true>
}
type ApiAccountsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/accounts_controller.ts').default['show'], false>
}
export interface ApiDefinition {
  'auth': {
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$post': AuthLogoutPost;
    };
  };
  'api': {
    'accounts': {
      '$url': {
      };
      '$get': ApiAccountsGetHead;
      '$head': ApiAccountsGetHead;
      '$post': ApiAccountsPost;
      ':id': {
        '$url': {
        };
        '$get': ApiAccountsIdGetHead;
        '$head': ApiAccountsIdGetHead;
      };
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
